[package]
name = "rjni"
version = "0.1.0"
authors = ["Liangcheng Juves <email@lcjuves.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
toml = "0.5.8"

[lib]
name = "rjni"
