[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-s"]

# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=/DEBUG:NONE"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
