[package]
name = "ferris-says"
version = "0.1.0"
authors = ["Liangcheng Juves <liangchengj@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
