# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "liangchengj/develop-environment:jit"

stages:
  - check
  - test

check:cargo:
  stage: check
  script:
    - rustc --version && cargo --version # Print version info
    - cargo check
    - cargo build

test:cargo:
  stage: test
  script:
    - cargo test --workspace --exclude wkrobot --exclude xlsx-example -- --nocapture
