workspace.members = [
    "base16",
    "base32",
    "base64",
    "cityhash",
    "demo",
    "ferris-says",
    "fmedia",
    "hello-rocket",
    "hello-rust",
    "hex-string",
    "io",
    "rcallc",
    "regexp",
    "rfserv",
    "rgrep",
    "rjni",
    "rotp",
    "tcp-client",
    "tcp-server",
    "wasm-game-of-life",
    "xlsx-example",
    "wkrobot",
]
