/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallJNI */

#ifndef _Included_CallJNI
#define _Included_CallJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallJNI
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CallJNI_getVersion(JNIEnv *, jclass);

/*
 * Class:     CallJNI
 * Method:    defineClass
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;[BI)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_CallJNI_defineClass(JNIEnv *, jclass, jstring,
                                                  jobject, jbyteArray, jint);

/*
 * Class:     CallJNI
 * Method:    findClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_CallJNI_findClass(JNIEnv *, jclass, jstring);

/*
 * Class:     CallJNI
 * Method:    fromReflectedMethod
 * Signature: (Ljava/lang/reflect/Method;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallJNI_fromReflectedMethod(JNIEnv *, jclass,
                                                           jobject);

/*
 * Class:     CallJNI
 * Method:    fromReflectedField
 * Signature: (Ljava/lang/reflect/Field;)Ljava/io/PrintStream;
 */
JNIEXPORT jobject JNICALL Java_CallJNI_fromReflectedField(JNIEnv *, jclass,
                                                          jobject);

/*
 * Class:     CallJNI
 * Method:    toReflectedMethod
 * Signature: ()Ljava/lang/reflect/Method;
 */
JNIEXPORT jobject JNICALL Java_CallJNI_toReflectedMethod(JNIEnv *, jclass);

/*
 * Class:     CallJNI
 * Method:    getSystemOut
 * Signature: ()Ljava/io/PrintStream;
 */
JNIEXPORT jobject JNICALL Java_CallJNI_getSystemOut(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
