[package]
name = "genqrsvg"
version = "0.1.0"
edition = "2021"
authors = ["Liangcheng Juves <email@lcjuves.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
qrcode = "0.12.0"
