[package]
name = "rotp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.11.0"
sha-1 = "0.9.8"
sha2 = "0.9.8"
rb32 = { version = "0.1.0", path = "../base32" }
