[package]
name = "ruimpl"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A library for rust utility implements"
authors = ["Liangcheng Juves <email@lcjuves.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
