terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: liangchengj/denv:fedora-x86-64-0.1.2
  # before_script:
  #   - apk update
  variables:
    RAILS_ENV: "test"
    NODE_ENV: "test"
