[package]
name = "rfserv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmedia = "0.2.0"

[dependencies.lazy_static]
version = "1.4.0"
